apiVersion: v2
name: meta
description: Berserk Meta Service - Metadata management
type: application
version: 0.1.1
dependencies:
  - name: berserk-common
    version: "*"
    repository: "file://../berserk-common"
