apiVersion: v1
kind: Service
metadata:
  name: {{ include "meta.fullname" . }}
  labels:
    {{- include "meta.labels" . | nindent 4 }}
    component: backend
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "meta.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
