apiVersion: v2
name: janitor
description: Berserk Janitor Service - Background maintenance and segment merging
type: application
version: 1.0.10
appVersion: 1.0.6
dependencies:
  - name: berserk-common
    version: "*"
    repository: "file://../berserk-common"
