apiVersion: v2
name: janitor
description: Berserk Janitor Service - Background maintenance and segment merging
type: application
version: 0.1.1
appVersion: "1.0.0"
dependencies:
  - name: berserk-common
    version: "0.1.0"
    repository: "file://../berserk-common"
