{{ include "berserk-common.configmap.metadata" . }}
data:
  config.yaml: |
    bind: "0.0.0.0:{{ .Values.service.targetPort }}"
    query_endpoint: {{ .Values.config.queryEndpoint | quote }}
    meta_endpoint: {{ .Values.config.metaEndpoint | quote }}
    {{- include "berserk-common.observability-config" . | nindent 4 }}
