apiVersion: v2
name: query
description: Berserk Query Service - Query engine for observability data
type: application
version: 1.0.9
appVersion: 1.0.6
dependencies:
  - name: berserk-common
    version: "*"
    repository: "file://../berserk-common"
