apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingest.fullname" . }}
  labels:
    {{- include "ingest.labels" . | nindent 4 }}
    component: collector
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ingest.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.ports.otlpGrpc }}
      targetPort: {{ .Values.service.ports.otlpGrpc }}
      protocol: TCP
      name: otlp-grpc
    - port: {{ .Values.service.ports.otlpHttp }}
      targetPort: {{ .Values.service.ports.otlpHttp }}
      protocol: TCP
      name: otlp-http
    - port: {{ .Values.service.ports.telemetry }}
      targetPort: {{ .Values.service.ports.telemetry }}
      protocol: TCP
      name: telemetry
