apiVersion: v2
name: ui
description: Berserk UI - Web interface for query and visualization
type: application
version: 0.1.1
dependencies:
  - name: berserk-common
    version: "*"
    repository: "file://../berserk-common"
