apiVersion: v2
name: berserk
description: Berserk - High-performance observability data platform
type: application
version: 1.0.6

dependencies:
  - name: meta
    version: "*"
    condition: meta.enabled

  - name: query
    version: "*"
    condition: query.enabled

  - name: ingest
    version: "*"
    condition: ingest.enabled

  - name: janitor
    version: "*"
    condition: janitor.enabled

  - name: ui
    version: "*"
    condition: ui.enabled

  - name: nursery
    version: "*"
    condition: nursery.enabled
