apiVersion: v2
name: berserk
description: Berserk - High-performance observability data platform
type: application
version: 0.1.1
appVersion: "1.0.0"

dependencies:
  - name: meta
    version: "0.1.1"
    condition: meta.enabled

  - name: query
    version: "0.1.1"
    condition: query.enabled

  - name: ingest
    version: "0.1.1"
    condition: ingest.enabled

  - name: janitor
    version: "0.1.1"
    condition: janitor.enabled

  - name: ui
    version: "0.1.1"
    condition: ui.enabled

  - name: nursery
    version: "0.1.1"
    condition: nursery.enabled
