apiVersion: v2
name: ingest
description: Berserk Ingest Service - Tjalfe telemetry collector for data ingestion
type: application
version: 1.0.12
appVersion: 1.0.7
dependencies:
  - name: berserk-common
    version: "*"
    repository: "file://../berserk-common"
