apiVersion: v2
name: ingest
description: Berserk Ingest Service - Tjalfe telemetry collector for data ingestion
type: application
version: 0.1.1
dependencies:
  - name: berserk-common
    version: "*"
    repository: "file://../berserk-common"
