apiVersion: v2
name: nursery
description: Berserk Nursery Service - Baby segment management and promotion
type: application
version: 0.1.1
dependencies:
  - name: berserk-common
    version: "*"
    repository: "file://../berserk-common"
