apiVersion: v2
name: nursery
description: Berserk Nursery Service - Baby segment management and promotion
type: application
version: 1.0.11
appVersion: 1.0.6
dependencies:
  - name: berserk-common
    version: "*"
    repository: "file://../berserk-common"
